### ISSUE TITLE
Zone names instead of Landmark names

### ISSUE THREAD

**Issue by dt192** [wduda/TravelWindowII#124]
Would be nice to be able to have Zone names instead or in addition to the Landmark. For example Guide to Stangard even in the description just says Stangard in Eorlsmead, but the zone is actually Great River. I generally just want to go to a zone and don't care which exact town I end up in, so would be a lot quicker is I could see the list as zones in alphabetical order.

like...
Angmar: East
Angmar: West
Great River: Stangard
North Downs: Esteldin

**Comment by wduda** [comment]
If you have any suggestions how to treat special cases (i.e. should the new Carn Dum skill be under Angmar or separate category) I would appreciate that input :-) I can see the value of the idea.

**Comment by dt192** [comment]
Yeah, it should probably just follow whatever region it says in game. I'll put together a proposed list if that's any help and if you haven't started already.

![2023-05-03_13-37](https://user-images.githubusercontent.com/2612048/235918316-386c3e28-094b-4491-8036-132675c0ad91.png)
