### ISSUE TITLE
In v1.0.29alpha, The Order of the Eagles skill is not showing

### ISSUE THREAD

**Issue by wduda** [wduda/TravelWindowII#134]
Here is what's in the file: repLocations:AddSkill("Return to The Order of the Eagle", "0x700686FE", "Order of the Eagle (Rep)");

Here is what SHOULD be: repLocations:AddSkill("Return to the Order of the Eagle", "0x700686FE", "Order of the Eagle (Rep)");

Basically just lowercase the "T" in "The"

https://www.lotrointerface.com/downloads/fileinfo.php?id=1113#cmnt23657

**Comment by amjmaat** [comment]
repLocations:AddSkill("Return to the Order of the Eagle", "0x700686FE", "Order of the Eagle (Rep)");
    repLocations:AddSkill("Return to Umbar", "0x700686FF", "Umbar (Rep)");
    repLocations:AddSkill("Return to Dol Amroth", "0x70068700", "Dol Amroth (Rep U38)");
    repLocations:AddSkill("Return to Jax Phanâl", "0x70068701", "Jax Phanal (Rep)");
    repLocations:AddSkill("Return to Halrax", "0x70068702", "Harlax (Rep)");
    repLocations:AddSkill("Return to Lond Cirion", "0x70068703", "Lond Cirion (Rep)");
    repLocations:AddSkill("Return to the Ledger-keepers", "0x70068704", "Ledger-Keepers (Rep)");
