### ISSUE TITLE
Sorting does not work and is not saved

### ISSUE THREAD

**Issue by wduda** [wduda/TravelWindowII#15]

**Comment by wduda** [comment]
> 3- The "Return to Camp" skill always sorts to the end of the list even though I have it set to the top of the list in Travel Options->Sort. If I close the Travel Options window and then reopen it, some random travel skill appears at the top of the sort list and "Return to Camp" is back where it was before I moved it (near the bottom).

**Comment by wduda** [comment]
> 4- If I attempt to sort "Ost Guruth (Rep)" to a higher position on the list, it moves to the new position on the list but the icon position does not change in the skill display window. If I then close and reopen the "Travel Options" window, "Ost Guruth (Rep)" appears in the lower location from which I had previously moved it rather than where I placed it.

**Comment by wduda** [comment]
> he does not remember the order of the icons as I set them
--

**Comment by wduda** [comment]
> Forochel seems to be missing as well (I made sure it was checked) but whenever I try to sort one travel skill, a random one will move (Aka Whenever I move misty mountains, it moves Snowbourn instead).

**Comment by Dromo** [comment]
Im not sure how it is for others, but this is only issue for me after first load. First time loading - sorting skills does nothing. Reload plugin sort gets reset but sorting works and saves for reloads later fine, with some exceptions.

Trying to move Ost Guruth (Rep) did nothing and broke the sort again  - moving other skills stopped working too and had to reload again.

Moving Return to Camp moved the item below it instead (Return to Thorins Hall (Guide))

Can confirm, Forochel (Suri-Kyla) Guide is missing from the travel window. I have the skill and have it set in the selected tab, also can move it in the sort window, but it is not actually displayed in the main plugin window.
