### ISSUE TITLE
v1.2.0: german client, skill not detected: Rückkehr zur Taverne 'Zum Blutigen Adler'

### ISSUE THREAD

**Issue by AlterTobi** [wduda/TravelWindowII#161]
I've bought the rep skill, but the plugin (current git version as of today 05.01.2024) does not detect the skill.

[01/05 11:44:13 PM] Nicht erlernte Fertigkeit: Rückkehr zur Taverne 'Zum Blutigen Adler'

![image](https://github.com/wduda/TravelWindowII/assets/16866114/29a6cbfa-6eec-4b26-8b36-681fc9829152)

**Comment by whiterabbit963** [comment]
@AlterTobi Please see [whiterabbit963/TravelWindowII:tavern_debug](https://github.com/whiterabbit963/TravelWindowII/tree/tavern_debug)
Please post the output when the plugin is loaded. I expect to see 

`DOES THIS LOOK RIGHT: Rückkehr zur Taverne \qZum Blutigen Adler\q`

**Comment by AlterTobi** [comment]
output is

`DOES THIS LOOK RIGHT: Rückkehr zur Taverne "Zum Blutigen Adler"`

And something about warden, but I logged in with my champ.

`Warden coords 0x7004D73A not in dictionary`
`Warden dictionary coords 0x7004d73a not configured`

**Comment by whiterabbit963** [comment]
> output is
> 
> `DOES THIS LOOK RIGHT: Rückkehr zur Taverne "Zum Blutigen Adler"`

Cool. That makes sense why it failed. They must translate /q to a double quote.



> `Warden coords 0x7004D73A not in dictionary`
> `Warden dictionary coords 0x7004d73a not configured`

Good find! Fortunately, there is nothing to worry about. I added some coord verification based on skill ids for debugging. The skill is present in the maps if you logon to your warden, but it did not occur to me the id would be case sensitive. Easy update.

Thanks for troubleshooting! I'll work on some fixes for those issues.

**Comment by AlterTobi** [comment]
Looks good.

I've seen, you also changed the hunter and warden skills. Unfortunatly I can't tell you something about those since I don't own high level chars of those classes.

**Comment by whiterabbit963** [comment]
Unfortunately, neither do I. However, the localization in the dat files was composed the same. I am thinking it is safe to assume they will also be quoted in the same.
