### ISSUE TITLE
Error message on Check Untrained skills click

### ISSUE THREAD

**Issue by wduda** [wduda/TravelWindowII#163]
When clicking on the untrained skills button in options this error message is thrown.

[01/07 11:05:40 PM] ...s Online\Plugins\TravelWindowII\src\TravelWindow.lua:327: attempt to index field 'CaroTab' (a nil value)

**Comment by whiterabbit963** [comment]
Good find. Lua can be too loose with static vs object access. I also assumed TravelWindow was a global instance variable. I have a local fix. I'll do a PR on it once I can get my remaining updates rebased against main again.
