### ISSUE TITLE
DE: missing return to Dol Amroth (Western Gondor)

### ISSUE THREAD

**Issue by AlterTobi** [wduda/TravelWindowII#177]
When I check for untrained skills i get the message:

 Nicht erlernte Fertigkeit: Rückkehr nach Dol Amroth

![image](https://github.com/wduda/TravelWindowII/assets/16866114/8d163caf-1364-40c8-acea-65d77b484355)

Both Dol Amroth reputation skills (Western Gondor and Kings Gondor) have the same name in the German client.

**Comment by whiterabbit963** [comment]
Fix in PR #178
