### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by Morons** [wduda/TravelWindowII#20]
...s Online\Plugins\TravelWindowII\src\TravelWindow.lua:2: Unable to resolve package "Turbine.Debug".
...Rings Online\Plugins\TravelWindowII\src\__init__.lua:2: Failed to import package "TravelWindowII.src.TravelWindow".
...the Rings Online\Plugins\TravelWindowII\src\Main.lua:1: Failed to import package "TravelWindowII.src".

New Install with LPC V1.0.3.0

**Comment by wduda** [comment]
From the instructions:This plugin also requires the Turbine utilities that are available at:
http://content.turbine.com/sites/lot..._LuaPlugins.7z
This has to be extracted to your "Documents\The Lord of the Rings Online\Plugins" folder (if you are on Windows) so two folders called Turbine and TurbinePlugins show up there.

**Comment by Morons** [comment]
> 
> 
> It seems you are missing the Turbine package, since Turbine.Debug is found in the Turbine folder.
> 
> From the instructions:
> 
> ```
> This plugin also requires the Turbine utilities that are available at:
> http://content.turbine.com/sites/lotro/lua/Beta_LuaPlugins.7z
> This has to be extracted to your "Documents\The Lord of the Rings Online\Plugins" folder (if you are on Windows) so two folders called Turbine and TurbinePlugins show up there.
> ```
> 
> Plugin Compendium can install this if you install "Turbine Examples" like in the screenshot.
> 
> ![image](https://user-images.githubusercontent.com/2854511/103483784-f058c400-4de9-11eb-8475-7f5c931e2b14.png)
> 
> Please let me know if that worked, unfortunately, dependency handling is not perfectly straightforward with LOTRO plugins.

Yes Thanx fixed it
