### ISSUE TITLE
error with the German and French client

### ISSUE THREAD

**Issue by Lossensinome** [wduda/TravelWindowII#206]
Sorry for my bad English (google translated) :O

error with the German and French client

-on Version 2.4.0
Online\Plugins\TravelWindowII\src\TravelShortcut.l ua:252: attempt to concatenate field 'token' (a nil value)

-on Version 2.4.0b
Online\Plugins\TravelWindowII\src\TravelShortcut.l ua:262: attempt to concatenate field 'token' (a nil value)

**Comment by whiterabbit963** [comment]
@wduda Please see the typo in localestrings.lua at lines 781 and 782

**Comment by Lossensinome** [comment]
i have edir your tip with line 781 and 782.
now work the plugin perfecte

i dont unterstand whi this work after En
EN trick dont work with all Chars
that's why I later changed my thread in the Lotro interface
