### ISSUE TITLE
TravelWindowII works with one of two accounts in the same launcher

### ISSUE THREAD

**Issue by Nutzlos666** [wduda/TravelWindowII#207]
Sorry for my bad English (translated with Google Translate)

I have been using TravelWindowII for a very long time.
I have never had any problems before.
Since the update to 2.4.0b I have had the problem that the plugin works on one account, but on the other account I can only read the tab with the information in the add-on manager, I cannot click on the tab with the options, and I also don't have the icon in the game.
I have already uninstalled and reinstalled the plugin, also uninstalled and reinstalled it after restarting the operating system, and finally I uninstalled all the plugins and reinstalled it after restarting the operating system, without installing the other plugins.
I can use the plugin with my girlfriend's account without any problems, but not with my account.
I use the launcher via Steam. But I also tested it with the normal launcher and it's the same there. So it's not the launcher.
I really hope you can help me.

In one screenshot, my girlfriend's account (Dugy) is online and you can see the "Options" tab and the icon for the plugin.
In the other picture, my account (Kekskruemmel) is online and you can see that the "Options" tab is not clickable.

I use Windows 11 Pro x64.

The operating system, all game data and plugins are up to date.

best regards Nutzlos666

**Comment by wduda** [comment]
I will continue in German to make it easier for you

Ich kann keine Screenshots sehen. Spielt vllt einer von Euch auf Deutsch und deine Freundin auf Englisch?

Probiert bitte v2.4.1 wenn diese Version spaeter heute erscheint. Sonst waere es noch wichtig ob im Chat eine Fehlermeldung erscheint.

**Comment by Nutzlos666** [comment]
Hey, thx for your answer. 
I don't know, why the Screenshots not inside the first message.
I'll try v2.4.1 tomorrow and let U know about the working.
Both Accounts will still playing in german.

**Comment by wduda** [comment]
Let's keep the issue open. I would appreciate you letting me know if the new version has improved things or if we should dig deeper into the issue.

**Comment by Nutzlos666** [comment]
Good morning,

I updated to v2.4.1 and had a quick look at it with both accounts at the same time. I think it's working again.

I'll check it again when I play today or in the morning. If you don't hear from me again, then it's working without any problems.

Thank you for your quick response.
The work you're doing here is really great and very valuable. Thank you

**Comment by Nutzlos666** [comment]
I'm not sure why the post keeps getting closed. It's my first encounter with "github" and I mostly do it from my smartphone, so please excuse my lack of experience 🙈🤣

**Comment by Nutzlos666** [comment]
So the plugin works with the update v2.4.1. I'm really happy about it.
Thank you

There is the travel skill of the Ledger Keeper task; in German this would be "Buchhüter". Maybe you can update this in one of the upcoming updates?

**Comment by wduda** [comment]
Found the issue and captured in new item. Will be fixed in 2.4.2 that is coming soon

**Comment by Nutzlos666** [comment]
Das ist großartig, solltest du Hilfe bei Übersetzungen in Deutsch brauchen, sag gern bescheid
