### ISSUE TITLE
Bej Magha doesn't appear even when enabled

### ISSUE THREAD

**Issue by Stever1388** [wduda/TravelWindowII#245]
Doesn't look like this has been reported yet - Bej Magha doesn't seem to show up in the travel window anymore.

![image](https://github.com/user-attachments/assets/cb786317-b25b-43da-8bee-c8b9be92d180)

**Comment by whiterabbit963** [comment]
SSG changed the names on some of those skills. It seems they had a typo on their side. Some of the class skills were broken as well. I expect a few of the FR skill names they did not fix to change in the future as well.

**Comment by wduda** [comment]
Concrete reason: SSG changed Mâghda to Mâgha without the d. TW II has to rely on the skill names verbatim to identify the skills your character knows.

Fix will come with v2.5.0 that will also include U42 skills.
