### ISSUE TITLE
Changing options lags the client

### ISSUE THREAD

**Issue by Dromo** [wduda/TravelWindowII#28]
Changing options like Selecting the skills, changing skill order or changing opacity of the window and icon lags the client. It is especially visible while dragging the opacity sliders - as i basically cannot drag them due to the lag it cause.

**Comment by wduda** [comment]
Thanks for the report! Not as noticeable for me, but should definitely be fixed. Will look into that firsthand.

**Comment by wduda** [comment]
I looked into this a little bit. It seems on every small change, the plugin saves its settings to file on disk, and that is lagging the client. I need to look at some other authors plugins to get some ideas how to manage this effectively.

**Comment by Dromo** [comment]
If i can suggest - only save changes to disk when closing the option window.

**Comment by wduda** [comment]
That was my intention! I just need to have some time to test not only write the code :-)
