### ISSUE TITLE
small mistake in German / kleiner fehler im Deutsch

### ISSUE THREAD

**Issue by Lossensinome** [wduda/TravelWindowII#38]
small mistake in German
kleiner fehler im Deutsch

alt / old
`repLocations:AddSkill("Rückkehr nach Thal.", "0x7004D738", "Thal (Ruf)");`

neu ohne . / new without .
`repLocations:AddSkill("Rückkehr nach Thal", "0x7004D738", "Thal (Ruf)");`

**Comment by wduda** [comment]
Danke! Wird behoben so schnell wie ich ein neues Release veroeffentlichen kann.
