### ISSUE TITLE
Automate build and release process

### ISSUE THREAD

**Issue by wduda** [wduda/TravelWindowII#4]
Create a build script that will create a fully working new zip file.

**Comment by djhenderson** [comment]
Please try to integrate this with the GitHub release process so a custom watch for releases will notify watchers. The release asset should be the zip file you upload to lotro interface.

**Comment by wduda** [comment]
This is an old ticket, but I feel like this would be great to actually run via Github Actions or some other form of CI, rather than a local script. I will rename the issue to "Automate build and release process I guess :-)
