### ISSUE TITLE
Not showing all the milestones

### ISSUE THREAD

**Issue by Morons** [wduda/TravelWindowII#40]
I bought extra Milestone slots and only the default milestone show!
Had to go back to TravelWindow (Original) where they do show properly
Also I miss the scan for missing skills to add new Travel skills in Hunter etc.

**Comment by wduda** [comment]
Hey, that seems weird, as it still works for me in the English client at least, will all 11 milestone skills.

Which language do you play in?
Have you installed the latest version, 1.0.8beta?
Have you checked the plugin options and made sure all milestone skills there are actually enabled? Rightclick on the travel window icon, open options, go to the second tab.

**Comment by wduda** [comment]
I am also not understanding what you mean by scan to add new hunter skills. Skills should show up automatically once you relog after you learn them (that could be improved so relog is not necessary, will create a separate issue for that). 

There is a button on the second tab of the options to check for untrained skills, but that does not add any new skills to the list.

So in sum, there is neither the need nor the possibility to add new skills manually, and I am wondering what you are referring to.

**Comment by wduda** [comment]
Without further response I will have to close this as not verified. This will happen in another week from now.

**Comment by Morons** [comment]
> Which language do you play in?
> Have you installed the latest version, 1.0.8beta?
> Have you checked the plugin options and made sure all milestone skills there are actually enabled? Rightclick on the travel window icon, open options, go to the second tab, make sure "return to" skills have the checkboxes set.
> Is the window large enough to show all skills or maybe you need to scroll?

Which language do you play in? English
Have you installed the latest version, 1.0.8beta? Latest Yes
Have you checked the plugin options and made sure all milestone skills there are actually enabled? Rightclick on the travel window icon, open options, go to the second tab, make sure "return to" skills have the checkboxes set. Yes
Is the window large enough to show all skills or maybe you need to scroll? Yes optimised and in Icon mode

Funny thing I just Removed the old TravelWindow, re-installed TWII 1.0.8beta and voila they are there - Thanx for the fix
