### ISSUE TITLE
Add alphabetic sorting option for Travel Skills

### ISSUE THREAD

**Issue by wduda** [wduda/TravelWindowII#8]

**Comment by whiterabbit963** [comment]
I have alphabetic sorting implemented, but I feel like it is too simple. Should we only sort within each dictionary, and concatenate the dictionaries in the order they are currently added? I like having the "Return to" milestone skills at the top of my list. I suppose the user could sort by alphabet then sort any miscellaneous skills they want.

I am also working on progression sorting (by level) and I have noticed that it would be easier to make the "default" sorting the progression sort. This would mean shuffling around the order in which AddSkill() in the dictionaries is called, but in many cases, they are already in the correct order.
