### ISSUE TITLE
Travel updates for U30

### ISSUE THREAD

**Issue by Lossensinome** [wduda/TravelWindowII#80]
**Deutsch / German**

wardenLocations:AddSkill("Appell in Azanulbizar", "0x7005aa8c", "Azanulbizar (Appell)");

hunterLocations:AddSkill("Führer nach Azanulbizar", "0x7005aa95", "Azanulbizar (Führer)");
hunterLocations:AddSkill("Führer nach Akrâz-zahar", "0x7005aa91", "Akrâz-zahar (Führer)");

repLocations:AddSkill("Rückkehre nach Azanulbizar", "0x7005aa92", "Azanulbizar (Ruf)");
repLocations:AddSkill("Rückkehr nach Akrâz-zahar", "0x7005aa90", "Akrâz-zahar (Ruf)");

könnte sein (nicht  sicher) :
wardenLocations:AddSkill("Appell in Akrâz-zahar", "0x7005aa8f", "Akrâz-zahar (Appell)");

**Englisch**

wardenLocations:AddSkill("Muster in Azanulbizar", "0x7005aa8c", "Azanulbizar (Muster)");

hunterLocations:AddSkill("Guide to Azanulbizar", "0x7005aa95", "Azanulbizar (Guide)");
hunterLocations:AddSkill("Guide to Akrâz-zahar", "0x7005aa91", "Akrâz-zahar (Guide)");

repLocations:AddSkill("Return to Azanulbizar", "0x7005aa92", "Azanulbizar (Rep)");
repLocations:AddSkill("Return to Akrâz-zahar", "0x7005aa90", "Akrâz-zahar (Rep)");

could be (not sure) :
wardenLocations:AddSkill("Muster in Akrâz-zahar", "0x7005aa8f", "Akrâz-zahar (Muster)");

**Französisch**

wardenLocations:AddSkill("Rassemblement à Azanulbizar", "0x7005aa8c", "Azanulbizar (Rassemblement)");

hunterLocations:AddSkill("Guide vers Azanulbizar", "0x7005aa95", "Azanulbizar (Guide)");
hunterLocations:AddSkill("Guide vers Akrâz-zahar", "0x7005aa91", "Akrâz-zahar (Guide)");

repLocations:AddSkill("Retour à Azanulbizar", "0x7005aa92", "Azanulbizar (Rep)");
repLocations:AddSkill("Retour à Akrâz-zahar", "0x7005aa90", "Akrâz-zahar (Rep)");

pourrait être (pas sûr) :
wardenLocations:AddSkill("Rassemblement à Akrâz-zahar", "0x7005aa8f", "Akrâz-zahar (Rassemblement)");

**Comment by wduda** [comment]
Adding you to the credits file!
