### ISSUE TITLE
Window resize doesn't save state

### ISSUE THREAD

**Issue by hemberger** [wduda/TravelWindowII#89]
If I make changes to the "Travel" window element (such as resizing), these changes do not save after logging out _unless_ I also open up the "Travel Options" window after making the change. If this is by design, it is not really intuitive, and has caused confusion in a few people I've discussed the issue with.

Thanks for all your work on this plugin. It's really helpful!

**Comment by wduda** [comment]
That will be fixed as it is not intended.
