### ISSUE TITLE
Fix sorting of milestone skills

### ISSUE THREAD

**Issue by wduda** [wduda/TravelWindowII#9]
Well here is part of the issue and it's a game issue - and a workaround:

When you open your Skills panel and go to Milestone Skills, the order they are listed in-game is messed up and is as follows:

Current
7
8
9
10
11
2
3
4
5
6

If you open the Travel Window Options and go to Sort, and set up the order in this way, then open Travel Window using Mode: Icon Grid, some of the icons don't match the numbers in the Options | Sort panel.

To make the icons match the order shown in the game's Milestone Skills list (which is whack), sort your skills in the Options | Sort window as follows:

Current
10
9
8
7
11
2
3
4
5
6

**Comment by djhenderson** [comment]
I came here to report the same problem. It is very annoying when you have more than 6 but not all of the higher milestone skills.

**Comment by Dromo** [comment]
According to [this forum post](https://www.lotro.com/forums/showthread.php?672863-How-do-I-rearrange-Milestone-Skills-into-the-correct-order); the order of the milestone skills in game depends on the order of purchase.

**Comment by djhenderson** [comment]
I carefully purchased the milestone skills in numeric order (not the order of listing in the store), and I have all my e-receipts from Xsolla to confirm this, When I purchased Milestone Skill VII, it did not appear when I checked milestone skill 7 in the Travel plugin. IIRC, it showed up when I checked milestone 10 in the plugin.

I expect that the skills listed when you attempt to bind to a milestone is sorted in GID order. (The GID is the Global ID, the internal code used to identify the milestone skill.)

**Comment by wduda** [comment]
I am looking into finding or creating a way to have a unique identifier for skills, so maybe there is a way to fix this problem in Travel Window II at least. Since Milestone skills have a unique ID I might be able to use that.

**Comment by wduda** [comment]
The issue was that the plugin was mixing up the pairs of skill name and skill ID. I.e. "Return Home 7" had the saved ID of "Return Home 10". Will be fixed with 1.0.7beta release.

**Comment by wduda** [comment]
I have used the sort order in the tooltip, where it says seventh, eighth, ninth etc skill.
