### ISSUE TITLE
Resizing window very laggy

### ISSUE THREAD

**Issue by dt192** [wduda/TravelWindowII#98]
Hi,

When I try to resize the travel window my fps feel like they tank.

[Youtube vid of the issue](https://youtu.be/G2gqLoBAQKg)

I've tried relogging and tried updating to latest version.

I actually don't think you should have resizing like this anyway, as it's very difficult to get the padding on the right to match the padding on the left. You might be better off just letting the user choose how many icons per row in the settings and set you width and length programmatically.

**Comment by whiterabbit963** [comment]
v1.3.0 should fix this. For some reason the project was updated but was not linked properly with this issue to update it as well.

**Comment by wduda** [comment]
It was just me forgetting to close the issue after testing v1.3.0 and confirming that lag is gone :-)

**Comment by whiterabbit963** [comment]
Brilliant! Manual errors are the best!
